### PR TITLE
add single fold commands

### PR DESCRIPTION
**Pull request by Keisir**

### CODE REVIEW

**Comment by Sachin-12** [comment]
Hi. I would love to have this feature. Any plans to merge it soon?

**Comment by Keisir** [comment]
Yes, i will merge and release a plugin update this weekend. Do you have a preferred shortcut for this command? I'm not quite sure what the right one would be.

I personally use multi stroke keybindings, but I don't think they are really good as a default.

//cc @Sachin-12

**Comment by Sachin-12** [comment]
Hi. My thoughts might be biased on this. I am a vim user and I have currently mapped fold all and expand all to `cmd-shift-down` and `cmd-shift-up` respectively.

```json
// My current config 
{
  "body": {
    "cmd-shift-s": "prettier:format",
    "cmd-p": "narrow-note:openOnlyInBook",
    "cmd-shift-p": "narrow-note:open"
  },
  ".CodeMirror textarea": {
    "cmd-shift-up": "code-fold:fold-all",
    "cmd-shift-down": "code-fold:unfold-all"
  }
}
```

> In my previous note taking apps `ctrl-up/cmd-up` collapses the heading and `ctrl-down/cmd-down` expands the heading. So for me this would be most optimal.  

But to achieve this I need to have separate commands so that I can map expand and collapse to 2 different keybindings.

I could see these bindings are already mapped to navigate to the top and bottom of the note. But I rarely use them as I mostly use vim bindings for navigation. Its better not to configure the default bindings and leave it to the user for configuration.

**Comment by Keisir** [comment]
I will add a fold and unfold (single) command too.

**Comment by Sachin-12** [comment]
> I will add a fold and unfold (single) command too.

Cool. Thanks for taking in my request!

**Pull request merged**
